### ISSUE TITLE
你好，请问你主板上的vga接口能用吗

### ISSUE THREAD

**Issue by hww-github** [YvesHo0968/H510M-I7-10700-EFI#1]
我的主板是h510m s2，只有一个vga接口，使用了很多方法都是黑屏无信号，你这个vga接口能正常显示吗

**Comment by YvesHo0968** [comment]
苹果10.8系统后不支持vga，我这边试过vga是不行的（HDMI、DVI、DP可以），核显有时候就要折腾核显接口定制，我这边用的是tb买的rx570二手免驱显卡（避开vga口，这个口有也不能用），显卡插上就能用了不需要配置，接3个显示器都没有问题，休眠这些也没问题，平时候也没关过机
